knp_snappy:
  temporary_folder: "%kernel.cache_dir%/snappy"
  pdf:
    enabled:    true
    binary:     xvfb-run -a /usr/bin/wkhtmltopdf
    options:    []

  image:
    enabled:    true
    binary:     xvfb-run -a /usr/bin/wkhtmltoimage
    options:    []
